### ISSUE TITLE
Docker Support

### ISSUE THREAD

**Issue by christiangalsterer** [eBay/collectbeat#3]
Hi,

first of all thanks for the great beat and open sourcing it.
I wanted to check if you already know when Docker support is available as currently don't use Kubernetes yet.

**Comment by vjsamuel** [comment]
@christiangalsterer we dont support it today. please keep an eye out on this. it could be useful:
https://github.com/elastic/beats/pull/5245

**Comment by vjsamuel** [comment]
Beats autodiscover is available now and it supports Docker discovery:
https://www.elastic.co/guide/en/beats/filebeat/master/configuration-autodiscover.html
https://www.elastic.co/guide/en/beats/metricbeat/master/configuration-autodiscover.html
