### ISSUE TITLE
Multiple namespaces

### ISSUE THREAD

**Issue by evilris** [eBay/collectbeat#8]
Hi,

Thanks for contributing this tool to opensource.

Is there any possibility to run collecbeat for all namespaces instead of passing one namespace ?

**Comment by mumoshu** [comment]
@evilris Hi! What's your end goal in doing so?
AFAICS, collectbeat runs within a specific namespace but is still able to collect logs and metrics from any namespace. So, running it per every namespace doesn't make sense to me.

**Comment by vjsamuel** [comment]
@evilris @mumoshu please take a look at `autodiscover` on Beats. most of collectbeat has been migrated into upstream beats.

Useful links:
https://www.elastic.co/guide/en/beats/filebeat/master/configuration-autodiscover.html
https://www.elastic.co/guide/en/beats/metricbeat/master/configuration-autodiscover.html
